import './styles/tokens.css';
import './styles/reset.css';
import './styles/base.css';
import './styles/header.css';
import './styles/hero.css';
import './styles/below-fold.css';
import './styles/services.css';
import './styles/projects-panels.css';
import './styles/process-horizontal.css';
import './styles/studio.css';
import './styles/cta-footer.css';
import './styles/cursor.css';

import { initPreloader } from './scripts/preloader.js';
import { bindPointerField } from './scripts/pointer-field.js';
import { initAtmosphere } from './scripts/atmosphere.js';
import { initMonument } from './scripts/monument.js';
import { initCtaSplit } from './scripts/cta.js';
import { initSmoothScroll } from './scripts/smooth-scroll.js';
import { initServicesPanels } from './scripts/services-panels.js';
import { initProjectPanels } from './scripts/projects-panels.js';
import { initProcessHorizontal } from './scripts/process-horizontal.js';
import { initStudio } from './scripts/studio.js';
import { initCtaFooter } from './scripts/cta-footer.js';
import { initBelowFold } from './scripts/below-fold.js';

initPreloader();
bindPointerField();
initAtmosphere();
initMonument();
initCtaSplit();
initSmoothScroll();
initServicesPanels();
initProjectPanels();
initProcessHorizontal();
initStudio();
initCtaFooter();
initBelowFold();
